### ISSUE TITLE
"Congelación" del cliente una vez iniciado

### ISSUE THREAD

**Issue by jarufe** [manudona92/MapantESP#21]
Después de preparar los parámetros necesarios en el cliente, al darle al botón "Iniciar" la ventana se queda "congelada", no pudiendo moverla ni pulsar ningún botón u opción. La primera vez que quise probar las múltiples instancias no pude hacerlo, ya que le di a "Iniciar" antes de haber creado todas las instancias que quería.
¿Sería interesante cambiar el texto del botón para que ya no ponga "Iniciar" si ya está iniciado? La secuencia podría ser "Iniciar", "Procesando..." En mi caso, yo gestiono la alternativa "Iniciar" / "Parar" (en realidad no paro inmediatamente sino que impido que se generen nuevos procesamientos a medida que se vayan acabando los que están en curso) 
Si está en modo "Auto", ¿cómo se puede parar de procesar si ya no quieres continuar?
Mientras escribo esto me he dado cuenta de que ahora tengo 4 instancias (había lanzado 3 inicialmente), la última de ellas sin arrancar el proceso. ¿Será que me ha cogido alguna pulsación del ratón sobre el botón de "Nueva instancia" después de haberle dado a "Iniciar" en la primera de ellas?

**Comment by agustincaballero** [comment]
Ahora mismo la única forma de parar el proceso es cerrar la ventana del KP, lo cual aborta el proceso de la cuadrícula actual.
Naturalmente, faltan bastantes cosas por hacer en el cliente en cuanto a la interacción con el usuario, entre otras las que comentas de que no se quede "frito".
Sí, lo que comentas al final será eso, que le has dado al botón cuando estaba frito y la pulsación se ha ejecutado cuando ha revivido.
