### ISSUE TITLE
Cuadrículas que se quedan en estado "Renderizando"

### ISSUE THREAD

**Issue by jarufe** [manudona92/MapantESP#9]
En el momento en que ya quedan pocas cuadrículas de Lanzarote por procesar, veo que hay muchas que están en estado "Renderizando". Son todas de posiciones extremas, yo diría que ninguna toca tierra. 
¿Será porque no tienen datos vectoriales asociados y el proceso no termina de cambiarlas al estado "Procesada"?
Por ejemplo, cerca de Arrecife, cuadrículas: 6423204, 6443206, 6463206

**Comment by agustincaballero** [comment]
Cuando el cliente descarga una cuadrícula para procesar, en el servidor se marca como reservada. Si falla cualquier cosa (al procesar con KP o al renderizar) se queda en ese estado.
De momento prefiero que esto sea así, para analizar tranquilamente esos casos de fallos, las iré pasando yo manualmente de nuevo a estado disponible.
En el futuro, la idea será que esas cuadrículas pasen a disponibles para procesar de forma automática pasadas X horas.

**Comment by jarufe** [comment]
Ok, ahora que lo dices me suena que ya lo habías comentado anteriormente. Cierro esta entrada.
